api = "0.10"

[buildpack]
  id = "wilsonrf/com.wilsonfranca.aws-lambda-rie"
  homepage = "https://github.com/wilsonrf/aws-lambda-rie"
  name = "AWS Lambda RIE Buildpack"
  version = "0.0.2"

  [metadata]
  include-files = ["LICENSE", "README.adoc", "buildpack.toml", "linux/amd64/bin/run","linux/amd64/bin/build","linux/amd64/bin/detect", "linux/arm64/bin/run","linux/arm64/bin/build","linux/arm64/bin/detect"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.configurations]]
    build = false
    default = "false"
    description = "RIE Extension"
    name = "BP_RUNTIME_INTERFACE_EMULATOR"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"

[[stacks]]
  id = "com.wilsonfranca.stacks.amazonlinux.al2023"